# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import phasetwo_client
from phasetwo_client.paths.realm_orgs_org_id_roles_name import put  # noqa: E501
from phasetwo_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestRealmOrgsOrgIdRolesName(ApiTestMixin, unittest.TestCase):
    """
    RealmOrgsOrgIdRolesName unit test stubs
        Update role for this organization  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = put.ApiForput(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''




if __name__ == '__main__':
    unittest.main()
